export const SET_TICKET_LIST = "SET_TICKET_LIST";
export const CHOOSE_SEAT = "CHOOSE_SEAT"; 
export const RESET_CHOOSING_SEATS = "RESET_CHOOSING_SEATS";
export const BOOKING_TICKET = "BOOKING_TICKET";